---
datadog_site: datadoghq.eu
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: redmine health check status
        url: http://localhost
        timeout: 5
        method: GET
datadog_api_key: '{{ vault_datadog_api_key }}'
